### ISSUE TITLE
Error page when visiting the "Contributed" tab in "My favorites" page

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-photo-directory#31] opened 2024-12-04 10:21 UTC
**Describe the bug**
If you go to "My favorites" page and click on the "Contributed" tab, you will see an error page.

**To Reproduce**
1. Log in with your WordPress account
2. Click on "My favorites" link in local nav
3. Click on the "Contributed" tab

**Expected behavior**
It should show an empty state content in the same page. Here is a link to [the mockup](https://www.figma.com/design/j5lxNGoGKlzhSfhYNFQAxZ/Photos-Directory?node-id=3918-7615&node-type=frame&m=dev) made for this case. 

**Screenshots**

![Image](https://github.com/user-attachments/assets/04c7230d-868a-47cc-8652-080a23c68a36)

**Comment by ndiego** [comment] 2024-12-04 12:31
Confirmed. I get the same 404 page.

**Comment by ryelle** [comment] 2024-12-04 19:38
Ah, [WP will not 404 if the user is a member of the site](https://github.com/WordPress/wordpress-develop/blob/9558c1f48a5d118791e09a0184d22b4872714b7b/src/wp-includes/class-wp.php#L778), that's why it works locally for me. I can preempt that to prevent the 404 on all author archives.

**Comment by coffee2code** [comment] 2024-12-04 19:39
@ryelle I'm about to land the fix for this if you aren't about to yourself.

**Comment by ryelle** [comment] 2024-12-04 19:46
Oh I didn't realize you were working on this, I should have assigned myself when I started looking into it. I've already got the fix committed locally.

**Comment by ryelle** [comment] 2024-12-04 19:47
Okay, I'll revert my local commit 😆

**Closed as completed** 2024-12-04 19:47 UTC
Labels: [Component] Backend

**Comment by ryelle** [comment] 2024-12-04 19:48
This is how I'd solved it, since we took different approaches:

```php
/**
 * Prevents 404s for all author pages.
 *
 * By default, core will only prevent 404s on empty author archives
 * if the author is a member of the site. This preempts the handler
 * to prevent 404s for all author pages.
 *
 * @param bool     $preempt  Whether to short-circuit default header status handling. Default false.
 * @param WP_Query $query WordPress Query object.
 *
 * @return bool
 */
function prevent_author_404s( $preempt, $query ) {
	if ( ! $query->is_main_query() ) {
		return false;
	}

	$author = $query->get( 'author' );
	if ( $query->is_author && is_numeric( $author ) && $author > 0 ) {
		return true;
	}

	return false;
}
add_action( 'pre_handle_404', __NAMESPACE__ . '\prevent_author_404s', 10, 2 );
```

**Comment by coffee2code** [comment] 2024-12-04 19:51
🤦🏽 Sorry about that! I should have assigned it to myself as well. I like yours better and can make the change to use it.
