### ISSUE TITLE
Select a color filter with keyboard does not work

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-photo-directory#29] opened 2024-12-04 10:11 UTC
**Describe the bug**
When navigating the search and filter bar with the keyboard, selecting a color in the "Colors" popover filter does not work.

**To Reproduce**
1. Go to the homepage
2. Browse with your keyboard and focus on the Color filter
3. Press enter to open the filter
4. Browse with tab
5. Land on one color and press enter to select it
6. See the error

Sometimes the page loads. I can't identify how the bug works.

**Expected behavior**
It should select the item by showing the check icon and the focus ring.

<img src=https://github.com/user-attachments/assets/ab04e62f-2046-43cf-bd27-bbc5a71bde20 width=300>

**Screenshots**

https://github.com/user-attachments/assets/0d8cfa8b-3fc9-4e1c-9b19-c6fb583d7433

**Comment by ryelle** [comment] 2024-12-04 18:56
> Expected behavior
> [Enter] should select the item by showing the check icon and the focus ring.

These lists are implemented as checkboxes to get the native support for keyboard & screen reader users, and checkboxes are selected with <kbd>space</kbd>. You can see that on [this checkbox demo](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#try_it). People who regularly navigate with a keyboard will expect that, and use space to toggle the selection. This is also the expected behavior of a [listbox](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role), which is what this pattern is called when implemented from scratch.

What's happening here is "enter" is applying the filter, which is just reloading the page since nothing's selected yet. This is also, technically, correct behavior when inside a form, and a keyboard user might use this shortcut to avoid tabbing all the way to "Apply".

I'm inclined to close this, as this has been the behavior of these filters across the whole network, and changing it could go against keyboard users' expectations.

**Comment by fcoveram** [comment] 2024-12-05 08:30
All good then. Thanks for the clear explanation. We can close this issue.

**Closed as not planned** 2024-12-05 15:35 UTC
Labels: [Component] Blocks
